# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ClientView.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(778, 614)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.MenuIzquierdo = QtWidgets.QFrame(self.frame_2)
        self.MenuIzquierdo.setEnabled(True)
        self.MenuIzquierdo.setMinimumSize(QtCore.QSize(50, 0))
        self.MenuIzquierdo.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        self.MenuIzquierdo.setFont(font)
        self.MenuIzquierdo.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.MenuIzquierdo.setStyleSheet("background-color:rgb(255, 101, 101);\n"
"")
        self.MenuIzquierdo.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.MenuIzquierdo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.MenuIzquierdo.setLineWidth(1)
        self.MenuIzquierdo.setObjectName("MenuIzquierdo")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.MenuIzquierdo)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Desplegable1 = QtWidgets.QFrame(self.MenuIzquierdo)
        self.Desplegable1.setMaximumSize(QtCore.QSize(16777215, 50))
        self.Desplegable1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Desplegable1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Desplegable1.setObjectName("Desplegable1")
        self.MenuButton = QtWidgets.QPushButton(self.Desplegable1)
        self.MenuButton.setEnabled(True)
        self.MenuButton.setGeometry(QtCore.QRect(0, 0, 180, 50))
        self.MenuButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.MenuButton.setMouseTracking(False)
        self.MenuButton.setStyleSheet("QPushButton{\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    padding: 10px;\n"
"    text-align: left;\n"
"}\n"
"QPushButton:hover{ \n"
"    background-color:#c7bbff;\n"
"}")
        self.MenuButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/4619355-200.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.MenuButton.setIcon(QtGui.QIcon("interfaces/icons/bars.png"))
        self.MenuButton.setIconSize(QtCore.QSize(30, 30))
        self.MenuButton.setFlat(False)
        self.MenuButton.setObjectName("MenuButton")
        self.verticalLayout_2.addWidget(self.Desplegable1)
        self.Desplegable2 = QtWidgets.QFrame(self.MenuIzquierdo)
        self.Desplegable2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Desplegable2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Desplegable2.setObjectName("Desplegable2")
        self.InicioButton = QtWidgets.QPushButton(self.Desplegable2)
        self.InicioButton.setGeometry(QtCore.QRect(0, 40, 180, 50))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.InicioButton.setFont(font)
        self.InicioButton.setStyleSheet(" QPushButton{\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    padding: 10px;\n"
"    text-align: left;\n"
"}\n"
"QPushButton:hover{ \n"
"    background-color:#c7bbff;\n"
"}\n"
"\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/home.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.InicioButton.setIcon(icon1)
        self.InicioButton.setIconSize(QtCore.QSize(30, 30))
        self.InicioButton.setObjectName("InicioButton")
        self.CuentaButton = QtWidgets.QPushButton(self.Desplegable2)
        self.CuentaButton.setGeometry(QtCore.QRect(0, 100, 180, 50))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        self.CuentaButton.setFont(font)
        self.CuentaButton.setStyleSheet("QPushButton{\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    padding: 10px;\n"
"    text-align: left;\n"
"}\n"
"QPushButton:hover{ \n"
"    background-color:#c7bbff;\n"
"    \n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/user_transp.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.CuentaButton.setIcon(icon2)
        self.CuentaButton.setIconSize(QtCore.QSize(30, 30))
        self.CuentaButton.setObjectName("CuentaButton")
        self.CompraButton = QtWidgets.QPushButton(self.Desplegable2)
        self.CompraButton.setGeometry(QtCore.QRect(0, 160, 180, 50))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        self.CompraButton.setFont(font)
        self.CompraButton.setStyleSheet("QPushButton{\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    padding: 10px;\n"
"    text-align: left;\n"
"}\n"
"QPushButton:hover{ \n"
"    background-color:#c7bbff;\n"
"}")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/carrito_transp.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.CompraButton.setIcon(icon3)
        self.CompraButton.setIconSize(QtCore.QSize(30, 30))
        self.CompraButton.setObjectName("CompraButton")
        self.verticalLayout_2.addWidget(self.Desplegable2)
        self.horizontalLayout_2.addWidget(self.MenuIzquierdo)
        self.MenuDerecho = QtWidgets.QFrame(self.frame_2)
        self.MenuDerecho.setMinimumSize(QtCore.QSize(50, 0))
        self.MenuDerecho.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.MenuDerecho.setFrameShadow(QtWidgets.QFrame.Raised)
        self.MenuDerecho.setObjectName("MenuDerecho")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.MenuDerecho)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.Paginas = QtWidgets.QStackedWidget(self.MenuDerecho)
        self.Paginas.setObjectName("Paginas")
        self.PaginaInicio = QtWidgets.QWidget()
        self.PaginaInicio.setEnabled(True)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 222, 52))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(255, 222, 55))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 222, 52))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 222, 52))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(255, 222, 55))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(255, 222, 55))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 222, 52, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 222, 52))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(255, 222, 55))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 222, 52))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 222, 52))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(255, 222, 55))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(255, 222, 55))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 222, 52, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 222, 52))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(255, 222, 55))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 222, 52))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 222, 52))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(255, 222, 55))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(255, 222, 55))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 222, 52, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.PaginaInicio.setPalette(palette)
        self.PaginaInicio.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 222, 55, 255), stop:1 rgba(255, 255, 255, 255));\n"
"color: rgb(255, 222, 52);")
        self.PaginaInicio.setObjectName("PaginaInicio")
        self.tablaProductos = QtWidgets.QTableWidget(self.PaginaInicio)
        self.tablaProductos.setGeometry(QtCore.QRect(50, 160, 251, 401))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.tablaProductos.setPalette(palette)
        self.tablaProductos.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 8pt \"MS Shell Dlg 2\";\n"
"border-color: rgb(0, 0, 0);\n"
"color: rgb(0, 0, 0);\n"
"border-radius: 5px;\n"
"border-style: solid;\n"
"border-width: 1px;")
        self.tablaProductos.setColumnCount(2)
        self.tablaProductos.setObjectName("tablaProductos")
        self.tablaProductos.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tablaProductos.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tablaProductos.setHorizontalHeaderItem(1, item)
        self.lblListaProductos = QtWidgets.QLabel(self.PaginaInicio)
        self.lblListaProductos.setGeometry(QtCore.QRect(50, 120, 251, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lblListaProductos.setFont(font)
        self.lblListaProductos.setAutoFillBackground(False)
        self.lblListaProductos.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"color: rgb(255, 255, 127);\n"
"font: 18pt \"Century Gothic\";\n"
"border-color: rgb(0, 0, 0);\n"
"border-radius: 5px;\n"
"border-width: 2px;\n"
"font-color:rgb(0, 0, 0);")
        self.lblListaProductos.setAlignment(QtCore.Qt.AlignCenter)
        self.lblListaProductos.setObjectName("lblListaProductos")
        self.btnAgregar = QtWidgets.QPushButton(self.PaginaInicio)
        self.btnAgregar.setGeometry(QtCore.QRect(350, 530, 131, 31))
        self.btnAgregar.setStyleSheet("QPushButton{\n"
"    background-color: rgb(0, 170, 0);\n"
"    font: 75 10pt \"Century Gothic\";\n"
"    border-radius: 5px;\n"
"    border-width: 3px\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: #0000ff;\n"
"}"
"QPushButton:disabled{ \n"
"background-color:#a8a8a8;\n"
"color: rgb(255, 255, 255);\n"
"}")
        self.btnAgregar.setObjectName("btnAgregar")
        self.label = QtWidgets.QLabel(self.PaginaInicio)
        self.label.setGeometry(QtCore.QRect(330, -30, 320, 195))
        self.label.setStyleSheet("background-color: transparent;\n"
"image: url(:/backgraundImages/images/log.png);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.lblDetalle_4 = QtWidgets.QLabel(self.PaginaInicio)
        self.lblDetalle_4.setGeometry(QtCore.QRect(120, 50, 111, 41))
        self.lblDetalle_4.setStyleSheet("font: 75 18pt \"Century Gothic\";\n"
"background-color: #ff5500;\n"
"border-radius: 5px;\n"
"border-width: 5px;\n"
"color: rgb(255, 255, 255);")
        self.lblDetalle_4.setTextFormat(QtCore.Qt.AutoText)
        self.lblDetalle_4.setAlignment(QtCore.Qt.AlignCenter)
        self.lblDetalle_4.setWordWrap(False)
        self.lblDetalle_4.setObjectName("lblDetalle_4")
        self.tablaSeleccion = QtWidgets.QTableWidget(self.PaginaInicio)
        self.tablaSeleccion.setGeometry(QtCore.QRect(340, 170, 321, 271))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.tablaSeleccion.setPalette(palette)
        self.tablaSeleccion.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 8pt \"MS Shell Dlg 2\";\n"
"border-color: rgb(0, 0, 0);\n"
"color: rgb(0, 0, 0);\n"
"border-radius: 5px;\n"
"border-style: solid;\n"
"border-width: 1px;")
        self.tablaSeleccion.setColumnCount(3)
        self.tablaSeleccion.setObjectName("tablaSeleccion")
        self.tablaSeleccion.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tablaSeleccion.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tablaSeleccion.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tablaSeleccion.setHorizontalHeaderItem(2, item)
        self.lblListaProductos_2 = QtWidgets.QLabel(self.PaginaInicio)
        self.lblListaProductos_2.setGeometry(QtCore.QRect(360, 130, 271, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lblListaProductos_2.setFont(font)
        self.lblListaProductos_2.setAutoFillBackground(False)
        self.lblListaProductos_2.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"color: rgb(255, 255, 127);\n"
"font: 16pt \"Century Gothic\";\n"
"border-color: rgb(0, 0, 0);\n"
"border-radius: 5px;\n"
"border-width: 2px;\n"
"font-color:rgb(0, 0, 0);")
        self.lblListaProductos_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lblListaProductos_2.setObjectName("lblListaProductos_2")
        self.lblListaProductos_3 = QtWidgets.QLabel(self.PaginaInicio)
        self.lblListaProductos_3.setGeometry(QtCore.QRect(340, 450, 251, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lblListaProductos_3.setFont(font)
        self.lblListaProductos_3.setAutoFillBackground(False)
        self.lblListaProductos_3.setStyleSheet("background-color: transparent;\n"
"color: rgb(0, 0, 0);\n"
"font: 12pt \"Century Gothic\";\n"
"border-color: rgb(0, 0, 0);\n"
"border-radius: 5px;\n"
"border-width: 2px;\n"
"font-color:rgb(0, 0, 0);")
        self.lblListaProductos_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lblListaProductos_3.setObjectName("lblListaProductos_3")
        self.lblCantTotalProdSelec = QtWidgets.QLabel(self.PaginaInicio)
        self.lblCantTotalProdSelec.setGeometry(QtCore.QRect(590, 450, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lblCantTotalProdSelec.setFont(font)
        self.lblCantTotalProdSelec.setAutoFillBackground(False)
        self.lblCantTotalProdSelec.setStyleSheet("background-color: white;\n"
"color: rgb(0, 0, 0);\n"
"font: 11pt \"Century Gothic\";\n"
"border-color: rgb(0, 0, 0);\n"
"border-radius: 5px;\n"
"border-width: 2px;\n"
"border-style: solid;")
        self.lblCantTotalProdSelec.setText("")
        self.lblCantTotalProdSelec.setAlignment(QtCore.Qt.AlignCenter)
        self.lblCantTotalProdSelec.setObjectName("lblCantTotalProdSelec")
        self.lblListaProductos_5 = QtWidgets.QLabel(self.PaginaInicio)
        self.lblListaProductos_5.setGeometry(QtCore.QRect(320, 490, 251, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lblListaProductos_5.setFont(font)
        self.lblListaProductos_5.setAutoFillBackground(False)
        self.lblListaProductos_5.setStyleSheet("background-color: transparent;\n"
"color: rgb(0, 0, 0);\n"
"font: 12pt \"Century Gothic\";\n"
"border-color: rgb(0, 0, 0);\n"
"border-radius: 5px;\n"
"border-width: 2px;\n"
"font-color:rgb(0, 0, 0);")
        self.lblListaProductos_5.setAlignment(QtCore.Qt.AlignCenter)
        self.lblListaProductos_5.setObjectName("lblListaProductos_5")
        self.lblSubtotalSelec = QtWidgets.QLabel(self.PaginaInicio)
        self.lblSubtotalSelec.setGeometry(QtCore.QRect(550, 490, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lblSubtotalSelec.setFont(font)
        self.lblSubtotalSelec.setAutoFillBackground(False)
        self.lblSubtotalSelec.setStyleSheet("background-color: white;\n"
"color: rgb(0, 0, 0);\n"
"font: 11pt \"Century Gothic\";\n"
"border-color: rgb(0, 0, 0);\n"
"border-radius: 5px;\n"
"border-width: 2px;\n"
"border-style: solid;")
        self.lblSubtotalSelec.setText("")
        self.lblSubtotalSelec.setAlignment(QtCore.Qt.AlignCenter)
        self.lblSubtotalSelec.setObjectName("lblSubtotalSelec")
        self.Paginas.addWidget(self.PaginaInicio)
        self.PaginaCuenta = QtWidgets.QWidget()
        self.PaginaCuenta.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(23,166, 255, 255), stop:1 rgba(255, 255, 255, 255));")
        self.PaginaCuenta.setObjectName("PaginaCuenta")
        self.frameCuenta = QtWidgets.QFrame(self.PaginaCuenta)
        self.frameCuenta.setGeometry(QtCore.QRect(150, 180, 401, 291))
        self.frameCuenta.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.505955, y1:0.324, x2:0.511, y2:1, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
"border-radius: 10px;\n"
"")
        self.frameCuenta.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameCuenta.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameCuenta.setObjectName("frameCuenta")
        self.lblUsuario = QtWidgets.QLabel(self.frameCuenta)
        self.lblUsuario.setGeometry(QtCore.QRect(30, 30, 71, 16))
        self.lblUsuario.setStyleSheet("background-color: transparent;\n"
"color: rgb(255, 255, 255);\n"
"font: 75 10pt \"Century Gothic\";")
        self.lblUsuario.setObjectName("lblUsuario")
        self.lblEmail = QtWidgets.QLabel(self.frameCuenta)
        self.lblEmail.setGeometry(QtCore.QRect(30, 60, 71, 16))
        self.lblEmail.setStyleSheet("background-color: transparent;\n"
"color: rgb(255, 255, 255);\n"
"font: 75 10pt \"Century Gothic\";")
        self.lblEmail.setObjectName("lblEmail")
        self.lblDom = QtWidgets.QLabel(self.frameCuenta)
        self.lblDom.setGeometry(QtCore.QRect(30, 90, 71, 16))
        self.lblDom.setStyleSheet("background-color: transparent;\n"
"color: rgb(255, 255, 255);\n"
"font: 75 10pt \"Century Gothic\";")
        self.lblDom.setObjectName("lblDom")
        self.btnCerrarSesion = QtWidgets.QPushButton(self.frameCuenta)
        self.btnCerrarSesion.setGeometry(QtCore.QRect(60, 240, 101, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.btnCerrarSesion.setPalette(palette)
        self.btnCerrarSesion.setStyleSheet("QPushButton{\n"
"    background-color: rgb(0, 85, 255);\n"
"    color: rgb(255, 255, 255);\n"
"    font: 75 10pt \"Century Gothic\";\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: #ff0000;\n"
"}")
        self.btnCerrarSesion.setObjectName("btnCerrarSesion")
        self.lblUsuario_2 = QtWidgets.QLabel(self.frameCuenta)
        self.lblUsuario_2.setGeometry(QtCore.QRect(130, 30, 251, 16))
        self.lblUsuario_2.setStyleSheet("background-color: transparent;\n"
"color:#ffff7f;\n"
"font: 75 10pt \"Century Gothic\";")
        self.lblUsuario_2.setText("")
        self.lblUsuario_2.setObjectName("lblUsuario_2")
        self.lblEmail_2 = QtWidgets.QLabel(self.frameCuenta)
        self.lblEmail_2.setGeometry(QtCore.QRect(130, 60, 251, 16))
        self.lblEmail_2.setStyleSheet("background-color: transparent;\n"
"color:#ffff7f;\n"
"font: 75 10pt \"Century Gothic\";")
        self.lblEmail_2.setText("")
        self.lblEmail_2.setObjectName("lblEmail_2")
        self.lblDom_2 = QtWidgets.QLabel(self.frameCuenta)
        self.lblDom_2.setGeometry(QtCore.QRect(130, 90, 251, 16))
        self.lblDom_2.setStyleSheet("background-color: transparent;\n"
"color: #ffff7f;\n"
"font: 75 10pt \"Century Gothic\";")
        self.lblDom_2.setText("")
        self.lblDom_2.setObjectName("lblDom_2")
        self.lblBonif = QtWidgets.QLabel(self.frameCuenta)
        self.lblBonif.setGeometry(QtCore.QRect(30, 120, 141, 16))
        self.lblBonif.setStyleSheet("background-color: transparent;\n"
"color: rgb(255, 255, 255);\n"
"font: 75 10pt \"Century Gothic\";")
        self.lblBonif.setObjectName("lblBonif")
        self.lblBonif_2 = QtWidgets.QLabel(self.frameCuenta)
        self.lblBonif_2.setGeometry(QtCore.QRect(180, 120, 41, 20))
        self.lblBonif_2.setStyleSheet("background-color: transparent;\n"
"color: #ffff7f;\n"
"font: 75 10pt \"Century Gothic\";")
        self.lblBonif_2.setText("")
        self.lblBonif_2.setObjectName("lblBonif_2")
        self.btnHistorial = QtWidgets.QPushButton(self.frameCuenta)
        self.btnHistorial.setGeometry(QtCore.QRect(200, 240, 161, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.btnHistorial.setPalette(palette)
        self.btnHistorial.setStyleSheet("QPushButton{\n"
"    background-color: rgb(0, 85, 255);\n"
"    color: rgb(255, 255, 255);\n"
"    font: 75 10pt \"Century Gothic\";\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: #ff0000;\n"
"}")
        self.btnHistorial.setObjectName("btnHistorial")
        self.label_2 = QtWidgets.QLabel(self.PaginaCuenta)
        self.label_2.setGeometry(QtCore.QRect(330, -30, 320, 195))
        self.label_2.setStyleSheet("background-color: transparent;\n"
"image: url(:/backgraundImages/images/log.png);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.lblDetalle_2 = QtWidgets.QLabel(self.PaginaCuenta)
        self.lblDetalle_2.setGeometry(QtCore.QRect(30, 50, 281, 41))
        self.lblDetalle_2.setStyleSheet("font: 75 18pt \"Century Gothic\";\n"
"background-color: #ff5500;\n"
"border-radius: 5px;\n"
"border-width: 5px;\n"
"color: rgb(255, 255, 255);")
        self.lblDetalle_2.setTextFormat(QtCore.Qt.AutoText)
        self.lblDetalle_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lblDetalle_2.setWordWrap(False)
        self.lblDetalle_2.setObjectName("lblDetalle_2")
        self.Paginas.addWidget(self.PaginaCuenta)
        self.PaginaComprar = QtWidgets.QWidget()
        self.PaginaComprar.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(140,190, 22, 255), stop:1 rgba(255, 255, 255, 255));")
        self.PaginaComprar.setObjectName("PaginaComprar")
        self.tablaDetalle = QtWidgets.QTableWidget(self.PaginaComprar)
        self.tablaDetalle.setGeometry(QtCore.QRect(50, 210, 311, 361))
        self.tablaDetalle.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 8pt \"MS Shell Dlg 2\";\n"
"border-color: rgb(0, 0, 0);\n"
"color: rgb(0, 0, 0);\n"
"border-radius: 5px;\n"
"border-style: solid;\n"
"border-width: 1px;")
        self.tablaDetalle.setFrameShape(QtWidgets.QFrame.Box)
        self.tablaDetalle.setRowCount(0)
        self.tablaDetalle.setColumnCount(3)
        self.tablaDetalle.setObjectName("tablaDetalle")
        item = QtWidgets.QTableWidgetItem()
        self.tablaDetalle.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablaDetalle.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablaDetalle.setHorizontalHeaderItem(2, item)
        self.lblDetalle = QtWidgets.QLabel(self.PaginaComprar)
        self.lblDetalle.setGeometry(QtCore.QRect(60, 160, 271, 41))
        self.lblDetalle.setStyleSheet("font: 75 18pt \"Century Gothic\";\n"
"background-color: rgb(255, 255, 127);\n"
"border-radius: 5px;\n"
"border-width: 5px;")
        self.lblDetalle.setTextFormat(QtCore.Qt.AutoText)
        self.lblDetalle.setAlignment(QtCore.Qt.AlignCenter)
        self.lblDetalle.setWordWrap(False)
        self.lblDetalle.setObjectName("lblDetalle")
        self.btnCancelar = QtWidgets.QPushButton(self.PaginaComprar)
        self.btnCancelar.setGeometry(QtCore.QRect(420, 550, 141, 23))
        self.btnCancelar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnCancelar.setStyleSheet("QPushButton{\n"
"    background-color: rgb(255, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"    font: 75 10pt \"Century Gothic\";\n"
"    border-radius: 5px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: #008f00;\n"
"}"
"QPushButton:disabled{ \n"
"background-color:#a8a8a8;\n"
"}")
        self.btnCancelar.setObjectName("btnCancelar")
        self.btnConfirmar = QtWidgets.QPushButton(self.PaginaComprar)
        self.btnConfirmar.setGeometry(QtCore.QRect(420, 510, 141, 23))
        self.btnConfirmar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnConfirmar.setStyleSheet("QPushButton{\n"
"background-color: rgb(0, 170, 255);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 10pt \"Century Gothic\";\n"
"border-radius: 5px;\n"
"}\n"
"QPushButton:hover{ \n"
"    background-color:#008f00;\n"
"    \n"
"}"
"QPushButton:disabled{ \n"
"background-color:#a8a8a8;\n"
"}")
        self.btnConfirmar.setObjectName("btnConfirmar")
        self.lblSubtotal = QtWidgets.QLabel(self.PaginaComprar)
        self.lblSubtotal.setGeometry(QtCore.QRect(440, 240, 101, 31))
        self.lblSubtotal.setStyleSheet("font: 75 14pt \"Century Gothic\";\n"
"background-color: rgb(255, 255, 127);\n"
"border-radius: 5px;\n"
"border-width: 5px;")
        self.lblSubtotal.setTextFormat(QtCore.Qt.AutoText)
        self.lblSubtotal.setAlignment(QtCore.Qt.AlignCenter)
        self.lblSubtotal.setWordWrap(False)
        self.lblSubtotal.setObjectName("lblSubtotal")
        self.lblSubtotalImporte = QtWidgets.QLabel(self.PaginaComprar)
        self.lblSubtotalImporte.setGeometry(QtCore.QRect(410, 280, 161, 31))
        self.lblSubtotalImporte.setStyleSheet("font: 75 18pt \"Century Gothic\";\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 5px;\n"
"border-width: 5px;")
        self.lblSubtotalImporte.setText("")
        self.lblSubtotalImporte.setTextFormat(QtCore.Qt.AutoText)
        self.lblSubtotalImporte.setAlignment(QtCore.Qt.AlignCenter)
        self.lblSubtotalImporte.setWordWrap(False)
        self.lblSubtotalImporte.setObjectName("lblSubtotalImporte")
        self.lblBonificacion = QtWidgets.QLabel(self.PaginaComprar)
        self.lblBonificacion.setGeometry(QtCore.QRect(390, 330, 201, 31))
        self.lblBonificacion.setStyleSheet("font: 75 12pt \"Century Gothic\";\n"
"background-color: rgb(255, 255, 127);\n"
"border-radius: 5px;\n"
"border-width: 5px;")
        self.lblBonificacion.setTextFormat(QtCore.Qt.AutoText)
        self.lblBonificacion.setAlignment(QtCore.Qt.AlignCenter)
        self.lblBonificacion.setWordWrap(False)
        self.lblBonificacion.setObjectName("lblBonificacion")
        self.lblBonifImporte = QtWidgets.QLabel(self.PaginaComprar)
        self.lblBonifImporte.setGeometry(QtCore.QRect(410, 370, 161, 31))
        self.lblBonifImporte.setStyleSheet("font: 75 18pt \"Century Gothic\";\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 5px;\n"
"border-width: 5px;")
        self.lblBonifImporte.setText("")
        self.lblBonifImporte.setTextFormat(QtCore.Qt.AutoText)
        self.lblBonifImporte.setAlignment(QtCore.Qt.AlignCenter)
        self.lblBonifImporte.setWordWrap(False)
        self.lblBonifImporte.setObjectName("lblBonifImporte")
        self.lblTotal = QtWidgets.QLabel(self.PaginaComprar)
        self.lblTotal.setGeometry(QtCore.QRect(410, 420, 161, 31))
        self.lblTotal.setStyleSheet("font: 75 14pt \"Century Gothic\";\n"
"background-color: rgb(255, 255, 127);\n"
"border-radius: 5px;\n"
"border-width: 5px;")
        self.lblTotal.setTextFormat(QtCore.Qt.AutoText)
        self.lblTotal.setAlignment(QtCore.Qt.AlignCenter)
        self.lblTotal.setWordWrap(False)
        self.lblTotal.setObjectName("lblTotal")
        self.lblTotalImporte = QtWidgets.QLabel(self.PaginaComprar)
        self.lblTotalImporte.setGeometry(QtCore.QRect(410, 460, 161, 31))
        self.lblTotalImporte.setStyleSheet("font: 75 18pt \"Century Gothic\";\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 5px;\n"
"border-width: 5px;")
        self.lblTotalImporte.setText("")
        self.lblTotalImporte.setTextFormat(QtCore.Qt.AutoText)
        self.lblTotalImporte.setAlignment(QtCore.Qt.AlignCenter)
        self.lblTotalImporte.setWordWrap(False)
        self.lblTotalImporte.setObjectName("lblTotalImporte")
        self.label_3 = QtWidgets.QLabel(self.PaginaComprar)
        self.label_3.setGeometry(QtCore.QRect(330, -30, 320, 195))
        self.label_3.setStyleSheet("background-color: transparent;\n"
"image: url(:/backgraundImages/images/log.png);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.lblDetalle_3 = QtWidgets.QLabel(self.PaginaComprar)
        self.lblDetalle_3.setGeometry(QtCore.QRect(100, 50, 141, 41))
        self.lblDetalle_3.setStyleSheet("font: 75 18pt \"Century Gothic\";\n"
"background-color: #ff5500;\n"
"border-radius: 5px;\n"
"border-width: 5px;\n"
"color: rgb(255, 255, 255);")
        self.lblDetalle_3.setTextFormat(QtCore.Qt.AutoText)
        self.lblDetalle_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lblDetalle_3.setWordWrap(False)
        self.lblDetalle_3.setObjectName("lblDetalle_3")
        self.lblCantidadProductos_2 = QtWidgets.QLabel(self.PaginaComprar)
        self.lblCantidadProductos_2.setGeometry(QtCore.QRect(410, 200, 161, 31))
        self.lblCantidadProductos_2.setStyleSheet("font: 75 18pt \"Century Gothic\";\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 5px;\n"
"border-width: 5px;")
        self.lblCantidadProductos_2.setText("")
        self.lblCantidadProductos_2.setTextFormat(QtCore.Qt.AutoText)
        self.lblCantidadProductos_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lblCantidadProductos_2.setWordWrap(False)
        self.lblCantidadProductos_2.setObjectName("lblCantidadProductos_2")
        self.lblCantidadProductos = QtWidgets.QLabel(self.PaginaComprar)
        self.lblCantidadProductos.setGeometry(QtCore.QRect(370, 160, 231, 31))
        self.lblCantidadProductos.setStyleSheet("font: 75 14pt \"Century Gothic\";\n"
"background-color: rgb(255, 255, 127);\n"
"border-radius: 5px;\n"
"border-width: 5px;")
        self.lblCantidadProductos.setTextFormat(QtCore.Qt.AutoText)
        self.lblCantidadProductos.setAlignment(QtCore.Qt.AlignCenter)
        self.lblCantidadProductos.setWordWrap(False)
        self.lblCantidadProductos.setObjectName("lblCantidadProductos")
        self.Paginas.addWidget(self.PaginaComprar)
        self.verticalLayout_3.addWidget(self.Paginas)
        self.horizontalLayout_2.addWidget(self.MenuDerecho)
        self.verticalLayout.addWidget(self.frame_2)
        self.horizontalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.InicioButton.setText(_translate("MainWindow", "   Inicio"))
        self.CuentaButton.setText(_translate("MainWindow", "   Cuenta"))
        self.CompraButton.setText(_translate("MainWindow", "   Comprar"))
        item = self.tablaProductos.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Descripción"))
        item = self.tablaProductos.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Precio"))
        self.lblListaProductos.setText(_translate("MainWindow", "Lista de Productos"))
        self.btnAgregar.setText(_translate("MainWindow", "Agregar al Carrito"))
        self.lblDetalle_4.setText(_translate("MainWindow", "INICIO"))
        item = self.tablaSeleccion.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Descripción"))
        item = self.tablaSeleccion.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Cantidad"))
        item = self.tablaSeleccion.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Subtotal"))
        self.lblListaProductos_2.setText(_translate("MainWindow", "Productos Seleccionados"))
        self.lblListaProductos_3.setText(_translate("MainWindow", "Cantidad Total de Productos:"))
        self.lblListaProductos_5.setText(_translate("MainWindow", "Subtotal de la Selección:"))
        self.lblUsuario.setText(_translate("MainWindow", "Usuario:"))
        self.lblEmail.setText(_translate("MainWindow", "Email:"))
        self.lblDom.setText(_translate("MainWindow", "Domicilio:"))
        self.btnCerrarSesion.setText(_translate("MainWindow", "Cerrar Sesión"))
        self.lblBonif.setText(_translate("MainWindow", "Tarjeta de Beneficios:"))
        self.btnHistorial.setText(_translate("MainWindow", "Historial de Compras"))
        self.lblDetalle_2.setText(_translate("MainWindow", "Detalles de la Cuenta"))
        item = self.tablaDetalle.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Descripción"))
        item = self.tablaDetalle.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Cantidad"))
        item = self.tablaDetalle.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Subtotal"))
        self.lblDetalle.setText(_translate("MainWindow", "Detalle del Carrito"))
        self.btnCancelar.setText(_translate("MainWindow", "Cancelar Compra"))
        self.btnConfirmar.setText(_translate("MainWindow", "Confirmar Compra"))
        self.lblSubtotal.setText(_translate("MainWindow", "Subtotal"))
        self.lblBonificacion.setText(_translate("MainWindow", "Bonificación por Tarjeta"))
        self.lblTotal.setText(_translate("MainWindow", "Total a Pagar"))
        self.lblDetalle_3.setText(_translate("MainWindow", "COMPRAS"))
        self.lblCantidadProductos.setText(_translate("MainWindow", "Cantidad de Productos"))
import archivos_rc
