# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'HistorialCompras.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(466, 587)
        MainWindow.setStyleSheet("background-color: #cdd0ff;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(260, 20, 161, 22))
        self.comboBox.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comboBox.setEditable(False)
        self.comboBox.setFrame(True)
        self.comboBox.setModelColumn(0)
        self.comboBox.setObjectName("comboBox")
        self.tablaDetalleCompra = QtWidgets.QTableWidget(self.centralwidget)
        self.tablaDetalleCompra.setGeometry(QtCore.QRect(50, 80, 371, 331))
        self.tablaDetalleCompra.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 5px;\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"border-color: rgb(0, 0, 0);\n"
"color: rgb(0, 0, 0);")
        self.tablaDetalleCompra.setFrameShape(QtWidgets.QFrame.Box)
        self.tablaDetalleCompra.setRowCount(0)
        self.tablaDetalleCompra.setColumnCount(3)
        self.tablaDetalleCompra.setObjectName("tablaDetalleCompra")
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tablaDetalleCompra.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tablaDetalleCompra.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tablaDetalleCompra.setHorizontalHeaderItem(2, item)
        self.lblListaNroCompra = QtWidgets.QLabel(self.centralwidget)
        self.lblListaNroCompra.setGeometry(QtCore.QRect(50, 20, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lblListaNroCompra.setFont(font)
        self.lblListaNroCompra.setAutoFillBackground(False)
        self.lblListaNroCompra.setStyleSheet("background-color: transparent;\n"
"color: rgb(0, 0, 0);\n"
"font: 12pt \"Century Gothic\";\n"
"border-color: rgb(0, 0, 0);\n"
"border-radius: 5px;\n"
"border-width: 2px;\n"
"font-color:rgb(0, 0, 0);")
        self.lblListaNroCompra.setAlignment(QtCore.Qt.AlignCenter)
        self.lblListaNroCompra.setObjectName("lblListaNroCompra")
        self.lblListaProductos_4 = QtWidgets.QLabel(self.centralwidget)
        self.lblListaProductos_4.setGeometry(QtCore.QRect(50, 460, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lblListaProductos_4.setFont(font)
        self.lblListaProductos_4.setAutoFillBackground(False)
        self.lblListaProductos_4.setStyleSheet("background-color: transparent;\n"
"color: rgb(0, 0, 0);\n"
"font: 12pt \"Century Gothic\";\n"
"border-color: rgb(0, 0, 0);\n"
"border-radius: 5px;\n"
"border-width: 2px;\n"
"font-color:rgb(0, 0, 0);")
        self.lblListaProductos_4.setAlignment(QtCore.Qt.AlignCenter)
        self.lblListaProductos_4.setObjectName("lblListaProductos_4")
        self.lblListaProductos_6 = QtWidgets.QLabel(self.centralwidget)
        self.lblListaProductos_6.setGeometry(QtCore.QRect(180, 540, 171, 21))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lblListaProductos_6.setFont(font)
        self.lblListaProductos_6.setAutoFillBackground(False)
        self.lblListaProductos_6.setStyleSheet("background-color: transparent;\n"
"color: rgb(0, 0, 0);\n"
"font: 14pt \"Century Gothic\";\n"
"border-color: rgb(0, 0, 0);\n"
"border-radius: 5px;\n"
"border-width: 2px;\n"
"font-color:rgb(0, 0, 0);")
        self.lblListaProductos_6.setAlignment(QtCore.Qt.AlignCenter)
        self.lblListaProductos_6.setObjectName("lblListaProductos_6")
        self.lblListaProductos_3 = QtWidgets.QLabel(self.centralwidget)
        self.lblListaProductos_3.setGeometry(QtCore.QRect(50, 420, 241, 21))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lblListaProductos_3.setFont(font)
        self.lblListaProductos_3.setAutoFillBackground(False)
        self.lblListaProductos_3.setStyleSheet("background-color: transparent;\n"
"color: rgb(0, 0, 0);\n"
"font: 12pt \"Century Gothic\";\n"
"border-color: rgb(0, 0, 0);\n"
"border-radius: 5px;\n"
"border-width: 2px;\n"
"font-color:rgb(0, 0, 0);")
        self.lblListaProductos_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lblListaProductos_3.setObjectName("lblListaProductos_3")
        self.lblListaProductos_5 = QtWidgets.QLabel(self.centralwidget)
        self.lblListaProductos_5.setGeometry(QtCore.QRect(50, 500, 201, 21))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lblListaProductos_5.setFont(font)
        self.lblListaProductos_5.setAutoFillBackground(False)
        self.lblListaProductos_5.setStyleSheet("background-color: transparent;\n"
"color: rgb(0, 0, 0);\n"
"font: 12pt \"Century Gothic\";\n"
"border-color: rgb(0, 0, 0);\n"
"border-radius: 5px;\n"
"border-width: 2px;\n"
"font-color:rgb(0, 0, 0);")
        self.lblListaProductos_5.setAlignment(QtCore.Qt.AlignCenter)
        self.lblListaProductos_5.setObjectName("lblListaProductos_5")
        self.lblBonifImporte = QtWidgets.QLabel(self.centralwidget)
        self.lblBonifImporte.setGeometry(QtCore.QRect(310, 500, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lblBonifImporte.setFont(font)
        self.lblBonifImporte.setAutoFillBackground(False)
        self.lblBonifImporte.setStyleSheet("background-color: white;\n"
"color: rgb(0, 0, 0);\n"
"font: 11pt \"Century Gothic\";\n"
"border-color: rgb(0, 0, 0);\n"
"border-radius: 5px;\n"
"border-width: 2px;\n"
"border-style: solid;")
        self.lblBonifImporte.setText("")
        self.lblBonifImporte.setAlignment(QtCore.Qt.AlignCenter)
        self.lblBonifImporte.setObjectName("lblBonifImporte")
        self.lblCantTotalProd = QtWidgets.QLabel(self.centralwidget)
        self.lblCantTotalProd.setGeometry(QtCore.QRect(310, 420, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lblCantTotalProd.setFont(font)
        self.lblCantTotalProd.setAutoFillBackground(False)
        self.lblCantTotalProd.setStyleSheet("background-color: white;\n"
"color: rgb(0, 0, 0);\n"
"font: 11pt \"Century Gothic\";\n"
"border-color: rgb(0, 0, 0);\n"
"border-radius: 5px;\n"
"border-width: 2px;\n"
"border-style: solid;")
        self.lblCantTotalProd.setText("")
        self.lblCantTotalProd.setAlignment(QtCore.Qt.AlignCenter)
        self.lblCantTotalProd.setObjectName("lblCantTotalProd")
        self.lblSubtotalImporte = QtWidgets.QLabel(self.centralwidget)
        self.lblSubtotalImporte.setGeometry(QtCore.QRect(310, 460, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lblSubtotalImporte.setFont(font)
        self.lblSubtotalImporte.setAutoFillBackground(False)
        self.lblSubtotalImporte.setStyleSheet("background-color: white;\n"
"color: rgb(0, 0, 0);\n"
"font: 11pt \"Century Gothic\";\n"
"border-color: rgb(0, 0, 0);\n"
"border-radius: 5px;\n"
"border-width: 2px;\n"
"border-style: solid;")
        self.lblSubtotalImporte.setText("")
        self.lblSubtotalImporte.setAlignment(QtCore.Qt.AlignCenter)
        self.lblSubtotalImporte.setObjectName("lblSubtotalImporte")
        self.lblTotalImporte = QtWidgets.QLabel(self.centralwidget)
        self.lblTotalImporte.setGeometry(QtCore.QRect(310, 540, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lblTotalImporte.setFont(font)
        self.lblTotalImporte.setAutoFillBackground(False)
        self.lblTotalImporte.setStyleSheet("background-color: white;\n"
"color: rgb(0, 0, 0);\n"
"font: 11pt \"Century Gothic\";\n"
"border-color: rgb(0, 0, 0);\n"
"border-radius: 5px;\n"
"border-width: 2px;\n"
"border-style: solid;")
        self.lblTotalImporte.setText("")
        self.lblTotalImporte.setAlignment(QtCore.Qt.AlignCenter)
        self.lblTotalImporte.setObjectName("lblTotalImporte")
        self.lblListaNroCompra_2 = QtWidgets.QLabel(self.centralwidget)
        self.lblListaNroCompra_2.setGeometry(QtCore.QRect(50, 50, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lblListaNroCompra_2.setFont(font)
        self.lblListaNroCompra_2.setAutoFillBackground(False)
        self.lblListaNroCompra_2.setStyleSheet("background-color: transparent;\n"
"color: rgb(0, 0, 0);\n"
"font: 12pt \"Century Gothic\";\n"
"border-color: rgb(0, 0, 0);\n"
"border-radius: 5px;\n"
"border-width: 2px;\n"
"font-color:rgb(0, 0, 0);")
        self.lblListaNroCompra_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lblListaNroCompra_2.setObjectName("lblListaNroCompra_2")
        self.lblFecha = QtWidgets.QLabel(self.centralwidget)
        self.lblFecha.setGeometry(QtCore.QRect(300, 50, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lblFecha.setFont(font)
        self.lblFecha.setAutoFillBackground(False)
        self.lblFecha.setStyleSheet("background-color: transparent;\n"
"color: rgb(0, 0, 0);\n"
"font: 12pt \"Century Gothic\";\n"
"border-color: rgb(0, 0, 0);\n"
"border-radius: 5px;\n"
"border-width: 2px;\n"
"font-color:rgb(0, 0, 0);")
        self.lblFecha.setText("")
        self.lblFecha.setAlignment(QtCore.Qt.AlignCenter)
        self.lblFecha.setObjectName("lblFecha")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        item = self.tablaDetalleCompra.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Descripción"))
        item = self.tablaDetalleCompra.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Cantidad"))
        item = self.tablaDetalleCompra.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Subtotal"))
        self.lblListaNroCompra.setText(_translate("MainWindow", "Compra Nro.:"))
        self.lblListaProductos_4.setText(_translate("MainWindow", "Subtotal:"))
        self.lblListaProductos_6.setText(_translate("MainWindow", "Total:"))
        self.lblListaProductos_3.setText(_translate("MainWindow", "Cantidad Total de Productos:"))
        self.lblListaProductos_5.setText(_translate("MainWindow", "Bonificación por Tarjeta:"))
        self.lblListaNroCompra_2.setText(_translate("MainWindow", "Fecha:"))
