# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\Usuarios\rmarting13\Documentos\Tecnicatura Universitaria en Programación\1000PROGRAMADORES\ProyectoSuperMark\interfaces\pruebaQTd.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(479, 498)
        MainWindow.setStyleSheet("QMainWindow{\n"
"background-color=black;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.txt1 = QtWidgets.QLabel(self.centralwidget)
        self.txt1.setGeometry(QtCore.QRect(0, -30, 491, 521))
        self.txt1.setStyleSheet("*{\n"
"background-color:aquamarine;\n"
"}")
        self.txt1.setObjectName("txt1")
        self.usuarioL = QtWidgets.QLineEdit(self.centralwidget)
        self.usuarioL.setGeometry(QtCore.QRect(220, 180, 113, 20))
        self.usuarioL.setObjectName("usuarioL")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(150, 180, 47, 13))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(140, 220, 81, 16))
        self.label_2.setObjectName("label_2")
        self.contraL = QtWidgets.QLineEdit(self.centralwidget)
        self.contraL.setGeometry(QtCore.QRect(220, 220, 113, 20))
        self.contraL.setInputMask("")
        self.contraL.setText("")
        self.contraL.setFrame(True)
        self.contraL.setEchoMode(QtWidgets.QLineEdit.Password)
        self.contraL.setDragEnabled(False)
        self.contraL.setReadOnly(False)
        self.contraL.setObjectName("contraL")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(200, 270, 75, 23))
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 479, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.txt1.setText(_translate("MainWindow", "   SUPERMARK"))
        self.label.setText(_translate("MainWindow", "USUARIO"))
        self.label_2.setText(_translate("MainWindow", "CONTRASEÑA"))
        self.pushButton.setText(_translate("MainWindow", "INGRESAR"))
